server:
  port: 8087

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          default-filters:
            # added to prevent blocking due to Cors policy for web socket communication
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

          routes:
            - id: SALON-SERVICE
              uri: "lb://SALON-SERVICE"
              predicates:
                - Path= /salons/**, /api/salons/**, /api/admin/salons/**

            - id: USER-SERVICE
              uri: "lb://USER-SERVICE"
              predicates:
                - Path= /auth/**, /api/admin/users/**, /api/users/**, /users/**

            - id: SERVICE-OFFERING
              uri: "lb://SERVICE-OFFERING"
              predicates:
                - Path= /api/service-offerings/**

            - id: CATEGORY
              uri: "lb://CATEGORY-SERVICE"
              predicates:
                - Path= /api/categories/**

            - id: BOOKING
              uri: "lb://BOOKING-SERVICE"
              predicates:
                - Path= /api/bookings/**

            - id: PAYMENT
              uri: "lb://PAYMENT-SERVICE"
              predicates:
                - Path= /api/payment/**

            - id: NOTIFICATION
              uri: "lb://NOTIFICATION-SERVICE"
              predicates:
                - Path= /api/notifications/**

            - id: REVIEW
              uri: "lb://REVIEW-SERVICE"
              predicates:
                - Path= /api/reviews/**

      # default-filters:
      # - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      # global-cors:
      #   cors-configurations:
      #     '[/**]':
      #       allowedOrigins:
      #         - "http://localhost:5173"
      #         - "https://salon-booking-three.vercel.app"
      #       allowedMethods:
      #         - GET
      #         - POST
      #         - PUT
      #         - DELETE
      #         - OPTIONS
      #       allowedHeaders:
      #           - "*"
      #       allowCredentials: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/master/protocol/openid-connect/certs"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
#   endpoint:
#     env:
#       access: read_only

# info:
#   app:
#     name: "gateway server"
#     description: "gateway server for ecommerce website"
